//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eventManagement.WinUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eventManagement.WinUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali novi zapis.
        /// </summary>
        public static string Success_Insert {
            get {
                return ResourceManager.GetString("Success_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste napravili izmjene.
        /// </summary>
        public static string Success_Update {
            get {
                return ResourceManager.GetString("Success_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresa nije validna.
        /// </summary>
        public static string Validation_EmailInvalid {
            get {
                return ResourceManager.GetString("Validation_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje nije validno.
        /// </summary>
        public static string Validation_InputInvalid {
            get {
                return ResourceManager.GetString("Validation_InputInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalno 100 karaktera.
        /// </summary>
        public static string Validation_Max100 {
            get {
                return ResourceManager.GetString("Validation_Max100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno 3 a maksimalno 20 karaktera.
        /// </summary>
        public static string Validation_Min2Max20 {
            get {
                return ResourceManager.GetString("Validation_Min2Max20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno 2 a maksimalno 50 karaktera.
        /// </summary>
        public static string Validation_Min2Max50 {
            get {
                return ResourceManager.GetString("Validation_Min2Max50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno 3 a maksimalno 100 karaktera.
        /// </summary>
        public static string Validation_Min3Max100 {
            get {
                return ResourceManager.GetString("Validation_Min3Max100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke nisu iste.
        /// </summary>
        public static string Validation_PasswordMatch {
            get {
                return ResourceManager.GetString("Validation_PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno polje.
        /// </summary>
        public static string Validation_RequiredField {
            get {
                return ResourceManager.GetString("Validation_RequiredField", resourceCulture);
            }
        }
    }
}
